pipeline {
    agent any
    
    environment {
        IMAGE_NAME = "nodejs-sample"
        CONTAINER_NAME = "nodejs-container"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Anvesh7099/DIL_Client.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('node-hello-world') {
                    sh '''
                    echo "Building Docker image..."
                    docker build -t ${IMAGE_NAME}:latest .
                    '''
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                echo "Removing old container..."
                docker rm -f ${CONTAINER_NAME} || true

                echo "Starting new container..."
                docker run -d --name ${CONTAINER_NAME} -p 3000:3000 ${IMAGE_NAME}:latest

                echo "Deployment successful!"
                '''
            }
        }
    }
}

